# Generated by Django 2.2.5 on 2019-10-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20191009_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='summary',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
