# Generated by Django 2.2.5 on 2019-10-04 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190927_1135'),
        ('article', '0002_auto_20190928_1453'),
    ]

    operations = [
    ]
