# Generated by Django 2.2.5 on 2019-11-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlepost_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='summary',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
