# Generated by Django 2.2.5 on 2019-11-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20191112_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='summary',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
